// ScholarMitra - Comprehensive Scholarship Database (WebCraft Competition Ready)
const SCHOLARSHIPS_DATA = [
  {
    id: "nsp-post-matric",
    title: "NSP Post-Matric Scholarship for Minorities",
    provider: "Ministry of Minority Affairs (Govt. of India)",
    providerType: "Government",
    amount: 30000,
    amountDisplay: "₹30,000 / year + Admission Fees",
    deadline: "2026-09-20",
    verified: true,
    category: ["Minority", "OBC", "General", "EWS"],
    eligibleCourses: ["B.Tech / BE", "BCA", "B.Sc", "B.Com", "BA", "MBBS", "Diploma", "MCA", "MBA"],
    eligibleStates: ["All India"],
    minPercentage: 50,
    maxIncome: 200000,
    maxIncomeDisplay: "₹2.0 Lakhs / year",
    gender: "Any",
    yearOfStudy: ["1st Year", "2nd Year", "3rd Year", "4th Year", "Final Year"],
    requiredDocs: [
      "Aadhaar Card",
      "Income Certificate (Issued by competent authority)",
      "Minority Community Certificate",
      "Previous Year Marks Card (Min 50%)",
      "Bonafide Student Certificate",
      "Fee Receipt of Current Year",
      "Bank Passbook linked with Aadhaar"
    ],
    overview: "Provides financial assistance to meritorious students belonging to economically weaker sections of minority communities (Muslim, Christian, Sikh, Buddhist, Jain, Parsi) to pursue higher education.",
    officialUrl: "https://scholarships.gov.in",
    portalName: "National Scholarship Portal (NSP)",
    badgeColor: "green",
    tags: ["Government", "Minority", "Undergraduate", "Postgraduate"]
  },
  {
    id: "ssp-karnataka-postmatric",
    title: "Karnataka SSP Post-Matric Scholarship Scheme",
    provider: "Social Welfare & Backward Classes Dept, Govt. of Karnataka",
    providerType: "Government",
    amount: 45000,
    amountDisplay: "₹25,000 - ₹45,000 / year (Fee Reimbursement + Maintenance)",
    deadline: "2026-09-12",
    verified: true,
    category: ["SC", "ST", "OBC", "EWS"],
    eligibleCourses: ["B.Tech / BE", "BCA", "B.Sc", "B.Com", "Diploma", "MBBS", "MCA", "Postgraduate"],
    eligibleStates: ["Karnataka"],
    minPercentage: 50,
    maxIncome: 250000,
    maxIncomeDisplay: "₹2.5 Lakhs / year",
    gender: "Any",
    yearOfStudy: ["1st Year", "2nd Year", "3rd Year", "4th Year", "Final Year"],
    requiredDocs: [
      "Aadhaar Card & RD Number",
      "Valid Caste & Income Certificate (RD Number)",
      "SSLC & PUC / 12th Marks Card",
      "College Admission / Fee Receipt",
      "Bonafide Certificate / Hosteller Certificate",
      "Seeded Bank Account with NPCI / Aadhaar"
    ],
    overview: "Flagship scholarship program by the Government of Karnataka offering full/partial tuition fee reimbursement and monthly maintenance allowances for students pursuing higher studies in Karnataka.",
    officialUrl: "https://ssp.postmatric.karnataka.gov.in",
    portalName: "Karnataka State Scholarship Portal (SSP)",
    badgeColor: "purple",
    tags: ["Karnataka", "Government", "Fee Reimbursement", "State Quota"]
  },
  {
    id: "reliance-foundation-ug",
    title: "Reliance Foundation Undergraduate Scholarship",
    provider: "Reliance Foundation",
    providerType: "Corporate CSR",
    amount: 200000,
    amountDisplay: "Up to ₹2,00,000 over course duration",
    deadline: "2026-09-30",
    verified: true,
    category: ["General", "OBC", "SC", "ST", "EWS", "Minority", "PwD"],
    eligibleCourses: ["B.Tech / BE", "BCA", "B.Sc", "B.Com", "BA", "MBBS"],
    eligibleStates: ["All India"],
    minPercentage: 60,
    maxIncome: 1500000,
    maxIncomeDisplay: "₹15.0 Lakhs / year (Preference < ₹2.5L)",
    gender: "Any",
    yearOfStudy: ["1st Year"],
    requiredDocs: [
      "Passport Size Photograph",
      "Aadhaar Card",
      "12th Grade Marksheet",
      "Bonafide College Enrollment Letter",
      "Family Income Proof (ITR / Salary Slip / Income Cert)",
      "Disability Certificate (if applicable)"
    ],
    overview: "A prestigious scholarship supporting first-year undergraduate students with robust grants, leadership development programs, and peer mentorship throughout their degree.",
    officialUrl: "https://www.scholarships.reliancefoundation.org",
    portalName: "Reliance Foundation Portal",
    badgeColor: "blue",
    tags: ["Corporate CSR", "Merit-cum-Means", "Leadership", "First Year"]
  },
  {
    id: "aicte-pragati-girls",
    title: "AICTE Pragati Scholarship for Girl Students",
    provider: "All India Council for Technical Education (AICTE)",
    providerType: "Government",
    amount: 50000,
    amountDisplay: "₹50,000 / year (Contingency + College fees)",
    deadline: "2026-09-08",
    verified: true,
    category: ["General", "OBC", "SC", "ST", "EWS", "Minority", "Single Girl Child"],
    eligibleCourses: ["B.Tech / BE", "Diploma", "BCA", "MCA"],
    eligibleStates: ["All India"],
    minPercentage: 60,
    maxIncome: 800000,
    maxIncomeDisplay: "₹8.0 Lakhs / year",
    gender: "Female",
    yearOfStudy: ["1st Year", "2nd Year"],
    requiredDocs: [
      "10th & 12th Standard Marksheet",
      "AICTE-approved College Admission Allotment Letter",
      "Family Income Certificate (Issued by Tahsildar or higher)",
      "Aadhaar Card & Bank Account details",
      "Tuition Fee Receipt",
      "Parents' declaration of maximum 2 girls per family"
    ],
    overview: "Designed to empower young women pursuing technical degrees and diploma programs at AICTE-approved institutions across India, offering ₹50,000 annually for up to 4 years.",
    officialUrl: "https://www.aicte-india.org/schemes/students-development-schemes/Pragati",
    portalName: "AICTE / NSP Portal",
    badgeColor: "pink",
    tags: ["Government", "Women in STEM", "Technical", "AICTE"]
  },
  {
    id: "hdfc-parivartan-ecss",
    title: "HDFC Bank Parivartan’s ECSS Programme",
    provider: "HDFC Bank CSR",
    providerType: "Corporate CSR",
    amount: 75000,
    amountDisplay: "₹35,000 - ₹75,000 / year",
    deadline: "2026-09-18",
    verified: true,
    category: ["General", "OBC", "SC", "ST", "EWS", "Minority"],
    eligibleCourses: ["B.Tech / BE", "BCA", "B.Sc", "B.Com", "BA", "Diploma", "Postgraduate"],
    eligibleStates: ["All India"],
    minPercentage: 55,
    maxIncome: 250000,
    maxIncomeDisplay: "₹2.5 Lakhs / year",
    gender: "Any",
    yearOfStudy: ["1st Year", "2nd Year", "3rd Year", "4th Year"],
    requiredDocs: [
      "Previous Academic Year Marksheet",
      "Current Year Admission Proof (ID card / Admission Letter / Fee Receipt)",
      "Income Proof (Govt Issued Certificate / BPL Card / Salary Slip)",
      "Applicant Bank Account Passbook",
      "Aadhaar Card / Government Photo ID",
      "Crisis Proof (if applying under crisis category)"
    ],
    overview: "Aims to support students from underprivileged sections who are at risk of dropping out due to financial hardship or sudden personal crises.",
    officialUrl: "https://www.buddy4study.com/page/hdfc-bank-parivartans-ecss-programme",
    portalName: "HDFC Parivartan / Buddy4Study",
    badgeColor: "blue",
    tags: ["Corporate CSR", "Crisis Relief", "Undergraduate", "Merit-cum-Means"]
  },
  {
    id: "tata-pankh-scholarship",
    title: "Tata Capital Pankh Scholarship Programme",
    provider: "Tata Capital Limited",
    providerType: "Corporate CSR",
    amount: 50000,
    amountDisplay: "Up to ₹50,000 (or 80% of course tuition fee)",
    deadline: "2026-09-25",
    verified: true,
    category: ["General", "OBC", "SC", "ST", "EWS"],
    eligibleCourses: ["B.Tech / BE", "BCA", "B.Sc", "B.Com", "BA", "Diploma"],
    eligibleStates: ["All India"],
    minPercentage: 60,
    maxIncome: 400000,
    maxIncomeDisplay: "₹4.0 Lakhs / year",
    gender: "Any",
    yearOfStudy: ["1st Year", "2nd Year", "3rd Year"],
    requiredDocs: [
      "Photo Identity Proof (Aadhaar Card)",
      "Income Proof issued by competent govt authority",
      "Previous Qualifying Exam Marksheet (Min 60%)",
      "Current Academic Year Fee Receipt",
      "Bank Account Details of Applicant"
    ],
    overview: "Tata Capital initiative supporting deserving students pursuing general graduation, technical degrees, and diploma courses to ensure uninterrupted education.",
    officialUrl: "https://www.tatacapital.com/csr",
    portalName: "Tata Capital CSR Portal",
    badgeColor: "orange",
    tags: ["Corporate CSR", "Tata Group", "Undergraduate", "Fee Assistance"]
  },
  {
    id: "kotak-kanya-scholarship",
    title: "Kotak Kanya Scholarship for Girl Students",
    provider: "Kotak Education Foundation",
    providerType: "Trust / Foundation",
    amount: 150000,
    amountDisplay: "₹1,50,000 / year until graduation",
    deadline: "2026-09-10",
    verified: true,
    category: ["General", "OBC", "SC", "ST", "EWS", "Minority"],
    eligibleCourses: ["B.Tech / BE", "MBBS", "BCA", "Architecture", "Design", "Integrated Law (LLB)"],
    eligibleStates: ["All India"],
    minPercentage: 75,
    maxIncome: 600000,
    maxIncomeDisplay: "₹6.0 Lakhs / year",
    gender: "Female",
    yearOfStudy: ["1st Year"],
    requiredDocs: [
      "Class 12 Marksheet (Min 75% score)",
      "College Admission Allotment Letter / Entrance Rank Card (JEE, NEET, CET)",
      "Income Certificate / ITR / Form 16",
      "Aadhaar Card",
      "Bank Account Details",
      "Fee Receipt from NAAC/NIRF accredited institution"
    ],
    overview: "Provides substantial financial assistance of ₹1.5 Lakhs per year to meritorious girl students from low-income families pursuing professional degrees in top institutes.",
    officialUrl: "https://kotakeducation.org/kotak-kanya-scholarship/",
    portalName: "Kotak Education Foundation",
    badgeColor: "pink",
    tags: ["Foundation", "Women in STEM", "Professional Degree", "High Grant"]
  },
  {
    id: "infosys-stem-stars",
    title: "Infosys Foundation STEM Stars Scholarship",
    provider: "Infosys Foundation",
    providerType: "Corporate CSR",
    amount: 100000,
    amountDisplay: "Up to ₹1,00,000 / year (Covers tuition, living & books)",
    deadline: "2026-09-28",
    verified: true,
    category: ["General", "OBC", "SC", "ST", "EWS"],
    eligibleCourses: ["B.Tech / BE", "BCA", "MBBS", "B.Sc"],
    eligibleStates: ["All India"],
    minPercentage: 70,
    maxIncome: 800000,
    maxIncomeDisplay: "₹8.0 Lakhs / year",
    gender: "Female",
    yearOfStudy: ["1st Year"],
    requiredDocs: [
      "Class 12 Passing Certificate & Scorecard",
      "JEE / State CET Scorecard & College Allotment letter",
      "Income Certificate issued by authorized govt officer",
      "Government Photo ID & Address proof",
      "College Fee Structure document"
    ],
    overview: "Encourages young women to excel in Science, Technology, Engineering, and Mathematics (STEM) by covering tuition, living expenses, and study materials.",
    officialUrl: "https://www.infosys.com/infosys-foundation/stem-stars.html",
    portalName: "Infosys Foundation Portal",
    badgeColor: "purple",
    tags: ["Infosys", "STEM", "Women in Tech", "Excellence"]
  },
  {
    id: "ongc-merit-scholarship",
    title: "ONGC Merit Scholarship for SC/ST & OBC",
    provider: "Oil and Natural Gas Corporation (ONGC)",
    providerType: "Government PSU",
    amount: 48000,
    amountDisplay: "₹48,000 / year (₹4,000 per month)",
    deadline: "2026-10-15",
    verified: true,
    category: ["SC", "ST", "OBC"],
    eligibleCourses: ["B.Tech / BE", "MBBS", "MBA", "M.Sc"],
    eligibleStates: ["All India"],
    minPercentage: 60,
    maxIncome: 200000,
    maxIncomeDisplay: "₹2.0 Lakhs / year",
    gender: "Any",
    yearOfStudy: ["1st Year"],
    requiredDocs: [
      "Certified copy of Caste Certificate",
      "Proof of Annual Family Income",
      "Class 12th / Graduation Marksheet",
      "Proof of Admission to Professional Degree",
      "Bank Account Details (ECS Mandate Form)",
      "PAN Card / Aadhaar Card"
    ],
    overview: "ONGC Foundation grants financial support to meritorious students from marginalized communities enrolled in full-time engineering, medicine, and management programs.",
    officialUrl: "https://ongcscholar.org",
    portalName: "ONGC Scholar Portal",
    badgeColor: "green",
    tags: ["PSU", "Merit-cum-Means", "SC/ST/OBC", "Engineering & Medicine"]
  },
  {
    id: "aicte-saksham-pwd",
    title: "AICTE Saksham Scholarship for Differently-Abled",
    provider: "AICTE, Ministry of Education",
    providerType: "Government",
    amount: 50000,
    amountDisplay: "₹50,000 / year throughout course",
    deadline: "2026-09-15",
    verified: true,
    category: ["PwD", "General", "OBC", "SC", "ST", "EWS"],
    eligibleCourses: ["B.Tech / BE", "Diploma", "BCA", "MCA"],
    eligibleStates: ["All India"],
    minPercentage: 50,
    maxIncome: 800000,
    maxIncomeDisplay: "₹8.0 Lakhs / year",
    gender: "Any",
    yearOfStudy: ["1st Year", "2nd Year"],
    requiredDocs: [
      "Disability Certificate (Min 40% disability certified by competent medical authority)",
      "10th & 12th Marksheets",
      "AICTE Institute Admission Letter",
      "Family Income Certificate (< ₹8 LPA)",
      "Aadhaar Card & Bank Passbook"
    ],
    overview: "Dedicated scheme to encourage differently-abled students with not less than 40% disability to pursue technical education with self-reliance.",
    officialUrl: "https://www.aicte-india.org/schemes/students-development-schemes/Saksham",
    portalName: "AICTE National Portal",
    badgeColor: "teal",
    tags: ["Government", "Differently-Abled (PwD)", "Technical", "Empowerment"]
  },
  {
    id: "central-sector-csss",
    title: "Central Sector Scheme of Scholarships (CSSS)",
    provider: "Department of Higher Education (MHRD)",
    providerType: "Government",
    amount: 20000,
    amountDisplay: "₹12,000 / year (UG) to ₹20,000 / year (PG)",
    deadline: "2026-10-05",
    verified: true,
    category: ["General", "OBC", "SC", "ST", "EWS"],
    eligibleCourses: ["B.Tech / BE", "BCA", "B.Sc", "B.Com", "BA", "MBBS", "MCA", "MBA"],
    eligibleStates: ["All India"],
    minPercentage: 80,
    maxIncome: 450000,
    maxIncomeDisplay: "₹4.5 Lakhs / year",
    gender: "Any",
    yearOfStudy: ["1st Year", "2nd Year", "3rd Year", "4th Year", "Final Year"],
    requiredDocs: [
      "Class 12th Board Scorecard (Top 20th percentile)",
      "Income Certificate by Revenue Official",
      "College Admission Bonafide",
      "Aadhaar Card",
      "Aadhaar-seeded Bank Account Passbook"
    ],
    overview: "For meritorious students scoring above the 80th percentile in relevant stream in Class 12 board examinations to support their day-to-day college expenses.",
    officialUrl: "https://scholarships.gov.in",
    portalName: "National Scholarship Portal",
    badgeColor: "purple",
    tags: ["Central Govt", "Top Percentile", "Board Toppers", "All Streams"]
  },
  {
    id: "vidyasaarathi-acc-cement",
    title: "ACC Vidyasaarathi Higher Education Scholarship",
    provider: "ACC Limited & Vidyasaarathi",
    providerType: "Corporate CSR",
    amount: 40000,
    amountDisplay: "₹40,000 / year",
    deadline: "2026-09-14",
    verified: true,
    category: ["General", "OBC", "SC", "ST", "EWS"],
    eligibleCourses: ["B.Tech / BE", "BCA", "B.Sc", "Diploma", "Postgraduate"],
    eligibleStates: ["All India"],
    minPercentage: 60,
    maxIncome: 500000,
    maxIncomeDisplay: "₹5.0 Lakhs / year",
    gender: "Any",
    yearOfStudy: ["1st Year", "2nd Year", "3rd Year", "4th Year"],
    requiredDocs: [
      "Aadhaar Card & Address Proof",
      "Class 10th & 12th Marksheet",
      "Current Year College Fee Receipt",
      "Income Certificate from Govt Officer",
      "College ID Card"
    ],
    overview: "Facilitated by ACC Cements through NSDL Vidyasaarathi platform to support deserving undergraduate engineering and science students.",
    officialUrl: "https://www.vidyasaarathi.co.in",
    portalName: "Vidyasaarathi Portal",
    badgeColor: "orange",
    tags: ["NSDL", "Corporate CSR", "Undergraduate", "Direct Bank Transfer"]
  },
  {
    id: "santoor-womens-scholarship",
    title: "Santoor Women’s Scholarship Programme",
    provider: "Wipro Consumer Care and Wipro Cares",
    providerType: "Corporate CSR",
    amount: 24000,
    amountDisplay: "₹24,000 / year (₹72,000 for 3 years)",
    deadline: "2026-09-05",
    verified: true,
    category: ["General", "OBC", "SC", "ST", "EWS"],
    eligibleCourses: ["BCA", "B.Sc", "B.Com", "BA", "B.Tech / BE", "Diploma"],
    eligibleStates: ["Karnataka", "Andhra Pradesh", "Telangana", "Chhattisgarh"],
    minPercentage: 60,
    maxIncome: 300000,
    maxIncomeDisplay: "₹3.0 Lakhs / year",
    gender: "Female",
    yearOfStudy: ["1st Year"],
    requiredDocs: [
      "10th Standard Marks Card (State Board)",
      "12th Standard / Inter Marks Card",
      "College ID / Bonafide Certificate",
      "Aadhaar Card / Voter ID",
      "Bank Account Details"
    ],
    overview: "Dedicated to young women from underprivileged backgrounds who have completed schooling from government schools/colleges to pursue higher graduation.",
    officialUrl: "https://www.santoorscholarship.com",
    portalName: "Santoor Official Portal",
    badgeColor: "pink",
    tags: ["Wipro Cares", "Women Empowerment", "State Specific", "Undergraduate"]
  },
  {
    id: "pmss-ex-servicemen",
    title: "Prime Minister’s Scholarship Scheme (PMSS)",
    provider: "Kendriya Sainik Board, Ministry of Defence",
    providerType: "Government",
    amount: 36000,
    amountDisplay: "₹30,000/yr (Boys) & ₹36,000/yr (Girls)",
    deadline: "2026-10-20",
    verified: true,
    category: ["General", "OBC", "SC", "ST", "EWS", "Defence Quota"],
    eligibleCourses: ["B.Tech / BE", "BCA", "MBBS", "B.Sc", "MCA", "MBA"],
    eligibleStates: ["All India"],
    minPercentage: 60,
    maxIncome: null,
    maxIncomeDisplay: "No Family Income Ceiling",
    gender: "Any",
    yearOfStudy: ["1st Year"],
    requiredDocs: [
      "Ex-Servicemen ESM Certificate / Serving Certificate",
      "PPO / Discharge Book copy",
      "MEQ (Minimum Educational Qualification) 12th/Diploma Marksheet (Min 60%)",
      "Bonafide Certificate from College / University",
      "Aadhaar Card & Bank Account linked details"
    ],
    overview: "Encourages higher technical and professional education for the dependent wards and widows of Central Armed Police Forces, Assam Rifles & Defence personnel.",
    officialUrl: "https://ksb.gov.in/pm-scholarship.htm",
    portalName: "Kendriya Sainik Board (KSB)",
    badgeColor: "blue",
    tags: ["Defence Wards", "Central Govt", "Technical Courses", "Professional"]
  },
  {
    id: "mahadbt-postmatric",
    title: "Maharashtra MahaDBT Post-Matric Scholarship",
    provider: "Government of Maharashtra (OBC, SEBC, VJNT & Social Justice)",
    providerType: "Government",
    amount: 40000,
    amountDisplay: "100% Tuition Fee + Exam Fee + Maintenance",
    deadline: "2026-09-30",
    verified: true,
    category: ["SC", "ST", "OBC", "EWS", "Minority"],
    eligibleCourses: ["B.Tech / BE", "BCA", "B.Sc", "B.Com", "MBBS", "Diploma", "Postgraduate"],
    eligibleStates: ["Maharashtra"],
    minPercentage: 50,
    maxIncome: 250000,
    maxIncomeDisplay: "₹2.5 Lakhs / year",
    gender: "Any",
    yearOfStudy: ["1st Year", "2nd Year", "3rd Year", "4th Year", "Final Year"],
    requiredDocs: [
      "Domicile Certificate of Maharashtra",
      "Caste Certificate & Caste Validity Certificate",
      "Income Certificate issued by Tehsildar",
      "CAP Allotment Letter / College Admission receipt",
      "HSC / Previous year Marksheets",
      "Aadhaar seeded bank account proof"
    ],
    overview: "Official scholarship initiative by Maharashtra Government providing complete fee waivers and monthly living assistance for resident students.",
    officialUrl: "https://mahadbt.maharashtra.gov.in",
    portalName: "MahaDBT State Portal",
    badgeColor: "purple",
    tags: ["Maharashtra", "State Govt", "Full Fee Waiver", "MahaDBT"]
  },
  {
    id: "jindal-foundation-merit",
    title: "Sitaram Jindal Foundation Scholarship Scheme",
    provider: "Sitaram Jindal Foundation",
    providerType: "Trust / Foundation",
    amount: 38400,
    amountDisplay: "₹2,500 - ₹3,200 / month (₹38,400 / yr)",
    deadline: "2026-11-30",
    verified: true,
    category: ["General", "OBC", "SC", "ST", "EWS", "Minority", "PwD"],
    eligibleCourses: ["B.Tech / BE", "BCA", "B.Sc", "B.Com", "BA", "MBBS", "Diploma", "MCA", "MBA"],
    eligibleStates: ["All India"],
    minPercentage: 65,
    maxIncome: 400000,
    maxIncomeDisplay: "₹4.0 Lakhs / year",
    gender: "Any",
    yearOfStudy: ["1st Year", "2nd Year", "3rd Year", "4th Year", "Final Year"],
    requiredDocs: [
      "Photocopy of SSLC / 10th & 12th Marks Card",
      "Income Certificate from Sub-Divisional Magistrate / Tehsildar",
      "Certificate of Fees paid / Fee receipt",
      "Certificate regarding hostel stay (if applicable)",
      "Disability / Ex-servicemen Certificate (if applicable)"
    ],
    overview: "Philanthropic scholarship providing monthly aid to poor students pursuing undergraduate, post-graduate, engineering, medical, and diploma courses without discrimination.",
    officialUrl: "https://www.sitaramjindalfoundation.org/scholarships.php",
    portalName: "Sitaram Jindal Foundation",
    badgeColor: "green",
    tags: ["Trust", "Monthly Stipend", "All Streams", "Pan-India"]
  },
  {
    id: "keep-india-smiling-colgate",
    title: "Keep India Smiling Foundational Scholarship",
    provider: "Colgate-Palmolive (India) Limited",
    providerType: "Corporate CSR",
    amount: 30000,
    amountDisplay: "₹30,000 / year for 3 - 4 years",
    deadline: "2026-09-22",
    verified: false,
    category: ["General", "OBC", "SC", "ST", "EWS"],
    eligibleCourses: ["B.Tech / BE", "BCA", "B.Sc", "B.Com", "BDS", "Diploma"],
    eligibleStates: ["All India"],
    minPercentage: 60,
    maxIncome: 500000,
    maxIncomeDisplay: "₹5.0 Lakhs / year",
    gender: "Any",
    yearOfStudy: ["1st Year"],
    requiredDocs: [
      "Passport size photo",
      "Valid ID proof (Aadhaar / PAN)",
      "Income proof (ITR / BPL card / Salary certificate)",
      "Class 12th scorecard (Min 60%)",
      "Fee receipt / College admission letter"
    ],
    overview: "Aims to provide foundational support to individuals who are deserving & meritorious but may lack the resources to pursue their educational dreams.",
    officialUrl: "https://www.colgate.com/en-in/scholarship",
    portalName: "Colgate CSR Portal",
    badgeColor: "orange",
    tags: ["Corporate CSR", "Undergraduate", "Under Verification", "Colgate"]
  },
  {
    id: "loreal-women-science",
    title: "L'Oréal India For Young Women In Science",
    provider: "L'Oréal India CSR",
    providerType: "Corporate CSR",
    amount: 250000,
    amountDisplay: "₹2,50,000 total (₹62,500 / year)",
    deadline: "2026-09-17",
    verified: true,
    category: ["General", "OBC", "SC", "ST", "EWS"],
    eligibleCourses: ["B.Tech / BE", "MBBS", "B.Sc", "Pure Science", "Biotechnology"],
    eligibleStates: ["All India"],
    minPercentage: 85,
    maxIncome: 600000,
    maxIncomeDisplay: "₹6.0 Lakhs / year",
    gender: "Female",
    yearOfStudy: ["1st Year"],
    requiredDocs: [
      "Class 10th & 12th Scorecard (Min 85% in PCM/PCB)",
      "Proof of admission in science/tech/medical college",
      "Family Income proof issued by Govt Authority",
      "Aadhaar Card",
      "Statement of Purpose / Essay"
    ],
    overview: "Prestigious award for young women students who have passed Class 12 with stellar academic record in science to pursue graduation in scientific fields.",
    officialUrl: "https://www.loreal.com/en/india/articles/commitments/for-young-women-in-science/",
    portalName: "L'Oréal Foundation Portal",
    badgeColor: "pink",
    tags: ["Women in Science", "High Merit (85%+)", "Prestige Award", "Research"]
  }
];

// Document master reference for checklist
const REQUIRED_DOCUMENTS_MASTER = [
  {
    id: "doc-aadhaar",
    name: "Aadhaar Card / National Photo ID",
    category: "Identity",
    description: "Must have active mobile number linked & NPCI / bank seeding completed.",
    tips: "Ensure name and Date of Birth match Class 10 records exactly.",
    requiredBy: ["All Schemes", "NSP", "SSP Karnataka", "AICTE", "CSR"]
  },
  {
    id: "doc-income",
    name: "Family Income Certificate",
    category: "Income",
    description: "Official certificate issued by Tahsildar / Revenue Authority (RD Number in Karnataka).",
    tips: "Must be within validity period (usually 1-3 years from issue date).",
    requiredBy: ["SSP Karnataka", "NSP", "HDFC", "Tata Pankh", "AICTE"]
  },
  {
    id: "doc-caste",
    name: "Caste / Category / Minority Certificate",
    category: "Category",
    description: "SC/ST/OBC/EWS/Minority proof issued by authorized revenue department.",
    tips: "Keep digital barcode or RD certificate number ready for quick verification.",
    requiredBy: ["SSP", "MahaDBT", "NSP Minority", "ONGC", "AICTE Saksham"]
  },
  {
    id: "doc-marks",
    name: "Previous Year Marks Card / Grade Sheet",
    category: "Academics",
    description: "10th, 12th (PUC) or previous semester marksheets attested by college.",
    tips: "Clear scan of original marksheet; avoid photocopies without college stamp.",
    requiredBy: ["All Schemes", "Central Sector CSSS", "Kotak Kanya", "Reliance"]
  },
  {
    id: "doc-bonafide",
    name: "Bonafide Student Certificate / Study Certificate",
    category: "College",
    description: "Official certificate signed by Principal/Dean with college seal and current year admission date.",
    tips: "Ensure current academic year (2026-27) is explicitly printed.",
    requiredBy: ["NSP", "SSP Karnataka", "AICTE Pragati", "Tata Pankh"]
  },
  {
    id: "doc-feereceipt",
    name: "College Fee Structure & Paid Fee Receipt",
    category: "College",
    description: "Official fee breakdown with challan number / online payment transaction ID.",
    tips: "Required for fee reimbursement claims and tuition grants.",
    requiredBy: ["SSP", "HDFC Parivartan", "AICTE", "Vidyasaarathi"]
  },
  {
    id: "doc-bank",
    name: "Aadhaar-Seeded Bank Passbook / Mandate Form",
    category: "Banking",
    description: "Passbook front page showing Account No, IFSC code, and student's name.",
    tips: "Account MUST be in the student's name and linked with Aadhaar NPCI mapper for Direct Benefit Transfer (DBT).",
    requiredBy: ["All Schemes", "Govt DBT", "NSP", "SSP"]
  },
  {
    id: "doc-photo",
    name: "Passport-Size Photograph & Signature",
    category: "Identity",
    description: "Recent color photograph on light background (< 200KB) and clear signature scan.",
    tips: "Maintain standard passport 35mm x 45mm proportions in JPG format.",
    requiredBy: ["All Schemes"]
  }
];

// Pre-built assistant FAQ intelligence
const ASSISTANT_KNOWLEDGE_BASE = [
  {
    keywords: ["bca", "computer", "b.tech", "engineering", "tech", "cs", "it"],
    title: "Scholarships for BCA / B.Tech / Computer Science Students",
    response: "For Computer Applications (BCA) and Technical degrees (B.Tech/BE), you have multiple high-value options:\n\n1. **AICTE Pragati Scholarship**: ₹50,000/yr for female technical students.\n2. **Reliance Foundation UG Scholarship**: Up to ₹2,00,000 for 1st-year students with min 60%.\n3. **HDFC Bank Parivartan's ECSS**: Up to ₹75,000 for students with family income under ₹2.5L.\n4. **Infosys Foundation STEM Stars**: Up to ₹1,00,000/yr for girls in STEM.\n5. **Karnataka SSP Post-Matric**: Full fee reimbursement for Karnataka residents (SC/ST/OBC/EWS).\n\nUse the **Find My Scholarships** profile form above to calculate your exact percentage match!",
    suggestedQuery: "What documents are needed for B.Tech scholarships?"
  },
  {
    keywords: ["ssp", "karnataka", "state scholarship portal", "rd number"],
    title: "Karnataka State Scholarship Portal (SSP) Guidance",
    response: "The **Karnataka SSP Post-Matric** is open for 2026-27 for SC, ST, OBC, EWS, and minority students enrolled in Karnataka institutions.\n\n**Key Requirements:**\n• Domicile in Karnataka\n• Valid RD Number for Caste & Income Certificate (< ₹2.5 Lakhs)\n• Aadhaar seeded to bank account via NPCI mapper\n• College bonafide registration\n\n**Benefits:** Covers full tuition fee reimbursement + annual maintenance allowance directly credited to your DBT account.",
    suggestedQuery: "How to check Aadhaar-bank seeding for SSP?"
  },
  {
    keywords: ["documents", "doc", "checklist", "certificate", "aadhaar", "income cert"],
    title: "Mandatory Document Checklist for Scholarship Applications",
    response: "To avoid application rejections, keep these 7 core documents ready in PDF/JPG (< 500KB):\n\n1. **Aadhaar Card** (active mobile linked)\n2. **Income Certificate** (< ₹2.5L / ₹4L / ₹8L depending on scheme)\n3. **Caste / Category Certificate** (if claiming reservation)\n4. **Previous Year Grade Sheet / 10th & 12th Marks Card**\n5. **College Bonafide / Admission Letter** for 2026-27\n6. **College Fee Receipt**\n7. **Aadhaar-Seeded Bank Passbook** in student's name\n\nTrack your readiness in our interactive **Document Checklist** section!",
    suggestedQuery: "What is NPCI bank seeding?"
  },
  {
    keywords: ["income", "2.5", "below 2.5", "low income", "poor", "financial", "family income"],
    title: "Best Scholarships for Family Income < ₹2.5 Lakhs / Year",
    response: "If your annual family income is under ₹2.5 Lakhs, you qualify for top priority government and CSR programs:\n\n• **Karnataka SSP Post-Matric**: Max fee reimbursement (Govt)\n• **NSP Post-Matric for Minorities**: ₹30,000/yr + fee aid\n• **HDFC Bank Parivartan ECSS**: Up to ₹75,000/yr\n• **Tata Capital Pankh Scholarship**: Up to ₹50,000\n• **Santoor Women’s Scholarship**: ₹24,000/yr\n\nMake sure your revenue-issued Income Certificate is updated for the current financial year.",
    suggestedQuery: "Can I apply for both Govt and CSR scholarships?"
  },
  {
    keywords: ["girls", "women", "female", "girl child", "stem"],
    title: "Exclusive Scholarships for Female Students",
    response: "Top dedicated scholarships for female students:\n\n1. **Kotak Kanya Scholarship**: ₹1,50,000/year for professional degrees (Min 75% in 12th).\n2. **AICTE Pragati**: ₹50,000/year for girls in engineering and technical programs.\n3. **Infosys Foundation STEM Stars**: ₹1,00,000/year for girls in STEM.\n4. **L'Oréal India Young Women in Science**: ₹2,50,000 for pure science/engineering.\n5. **Santoor Women’s Scholarship**: ₹24,000/year for general graduation.\n\nFilter by Category: 'Female' in the Explorer section to review full eligibility!",
    suggestedQuery: "What is Kotak Kanya eligibility?"
  },
  {
    keywords: ["deadline", "closing soon", "last date", "when to apply"],
    title: "Upcoming Deadlines & Time-Sensitive Schemes",
    response: "⚡ **Upcoming Deadlines to Watch:**\n\n• **Santoor Women's Scholarship**: Closing in 9 days (Sep 5)\n• **AICTE Pragati**: Closing in 12 days (Sep 8)\n• **Kotak Kanya Scholarship**: Closing in 14 days (Sep 10)\n• **Karnataka SSP Post-Matric**: Closing Sep 12\n• **HDFC Parivartan ECSS**: Closing Sep 18\n• **Reliance Foundation UG**: Closing Sep 30\n\nAlways submit at least 3-5 days before the deadline to prevent server timeout errors on government portals.",
    suggestedQuery: "Show verified scholarships only"
  },
  {
    keywords: ["multiple", "two scholarships", "can i apply for both"],
    title: "Can You Apply for Multiple Scholarships?",
    response: "Yes, you can apply to multiple scholarships, but observe these key rules:\n\n• **Govt + Govt**: You can generally receive only **ONE** central/state government tuition scholarship at a time (as DBT checks duplicate Aadhaar entries).\n• **Govt + Corporate CSR**: Most private CSR scholarships (like HDFC, Tata, Reliance) allow combining with non-conflicting government assistance, provided total aid does not exceed actual tuition and educational expenses.\n• **Always verify**: Read the specific scheme guidelines on the official portal before accepting duplicate awards.",
    suggestedQuery: "Which scholarships are 100% verified?"
  }
];
